version: "3.3"
services:
    web:
        image: brettt89/silverstripe-web:7.4-apache
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - database
        environment:
            - DOCUMENT_ROOT=/var/www/html/public
            - DB_CONNECTION=mysql
            - DB_HOST=database
            - DB_PORT=3306
            - DB_DATABASE=lumen_api
            - DB_USERNAME=root
            - DB_PASSWORD=

    database:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
